---
engines:
  phpcodesniffer:
    enabled: true
  phpmd:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
  phpmd:
    enabled: true
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- vendor/
- "assets/css/animate.css"
- "assets/css/animate.min.css"
- "assets/css/bootstrap.css"
- "assets/css/bootstrap.min.css"
- "assets/css/font-awesome-4.4.0/*"
- "assets/js/jquery.js"
- "assets/js/jquery-3.1.0.min.js"
- "assets/js/html5shiv-printshiv.min.js"
- "assets/js/bootstrap.min.js"
- "assets/js/jquery.easing.min.js"
- "assets/js/bootstrap.js"